name: "🧪 Test"

on:
  workflow_dispatch:
    null

jobs:
  test:
    name:
      "${{
        (startsWith(matrix.runner, 'ubuntu') && 'Linux')
        || (startsWith(matrix.runner, 'macos') && 'macOS')
        || (startsWith(matrix.runner, 'windows') && 'Windows')
      }}"

    strategy:
      matrix:
        runner:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"

        include:
          - pythons:
              - "3.8"
              - "3.9"
              - "3.10"
              - "3.11"
              - "3.12"
              - "3.13"

    runs-on: "${{ matrix.runner }}"
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v4"

      - name: "Setup Python"
        id: "setup-python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "${{ join(matrix.pythons, '\n') }}"

      - name: "Restore cache"
        id: "restore-cache"
        uses: "actions/cache@v4"
        with:
          key:
            "${{
              format(
                'test-os={0}-python={1}-hash={2}',
                matrix.runner,
                steps.setup-python.outputs.python-version,
                hashFiles(
                  'pyproject.toml',
                  'tox.ini'
                )
              )
            }}"
          path: |
            .venv/

      - name: "Identify venv path"
        shell: "bash"
        run: |
          echo 'venv-path=.venv/${{ runner.os == 'Windows' && 'Scripts' || 'bin' }}' >> "$GITHUB_ENV"

      - name: "Install tox"
        if: "steps.restore-cache.outputs.cache-hit != 'true'"
        run: |
          python -m venv .venv/
          ${{ env.venv-path }}/python -m pip install --upgrade pip setuptools wheel
          ${{ env.venv-path }}/python -m pip install tox

      - name: "Run tox"
        run: |
          ${{ env.venv-path }}/tox
